parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'

# ESLint rules: https://eslint.org/docs/rules/
# Typescript rules: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
rules:
  comma-style:
    - error
    - first
  key-spacing:
    - error
    - align: colon
  no-console: off
  indent: off
  '@typescript-eslint/indent':
    - error
    - 2
    - ObjectExpression: 0
  '@typescript-eslint/explicit-function-return-type':
    - warn
    - allowTypedFunctionExpressions: true
      allowExpressions: true
  # Ahhh why doesn't this work!!!
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
