parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'

# ESLint rules: https://eslint.org/docs/rules/
# Typescript rules: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
rules:
  comma-style:
    - error
    - first
  key-spacing:
    - error
    - align: colon
  no-console: 0
  semi: 0
  '@typescript-eslint/semi':
    - error
    - never
  indent: 0
  '@typescript-eslint/indent':
    - error
    - 2
    - ObjectExpression: 0
  '@typescript-eslint/explicit-function-return-type':
    - warn
    - allowTypedFunctionExpressions: true
      allowExpressions: true
  # can't do what I want with this because I define functions as variables
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-for-in-array': error

  # Experimental
  '@typescript-eslint/prefer-string-starts-ends-with': error
  '@typescript-eslint/restrict-plus-operands': error
